include: package:pedantic_mono/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude: 
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
linter:
  rules:
    prefer_relative_imports: true
    prefer_const_constructors: true
    always_use_package_imports: false
    sort_pub_dependencies: false

    use_setters_to_change_properties: false
    prefer_foreach: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
